require("config.remap")
require("config.set")
require("config.functions")
require("config.lazy")
require("config.snippets")
require("config.settitle")
require("vim._core.ui2").enable({ enable = true, msg = { target = "msg" } })
