return {}
-- return {
-- 	{
-- 		"lervag/vimtex",
-- 		lazy = false, -- we don't want to lazy load VimTeX
-- 		-- tag = "v2.15", -- uncomment to pin to a specific release
-- 		init = function()
-- 			-- VimTeX configuration goes here, e.g.
-- 			vim.g.vimtex_view_general_viewer = "SumatraPDF.exe" -- Make sure to include .exe
-- 			vim.g.vimtex_view_method = "general" -- This line should come first
-- 			vim.g.vimtex_view_general_options = "-reuse-instance @pdf"
-- 			vim.g.vimtex_view_general_options_latexmk = "-reuse-instance"
-- 			vim.g.vimtex_compiler_method = "latexmk"
-- 		end,
-- 	},
-- }
